on:
  push:
    branches:
      - 'hotfix/**'
permissions:
  contents: write
  pull-requests: write

name: release-please-hotfix
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: hellowrd-gitaction
          default-branch: hotfix/
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Other","hidden":false},
              {"type":"refactor","section":"Other","hidden":false},
              {"type":"ci","section":"Other","hidden":false},
              {"type":"test","section":"Other","hidden":false},
              {"type":"chore","section":"Other","hidden":true},
              {"type":"build","section":"Other","hidden":true}
            ]

